.TH SYSPROF 1 2005-12-27

.SH NAME
SYSPROF \- System-wide Linux Profiler

.SH SYNOPSIS
.B sysprof

.SH DESCRIPTION
.B sysprof is a sampling CPU profiler for Linux that uses a kernel module to profile the entire system, not just a single application. Sysprof handles shared libraries and applications do not need to be recompiled. In fact they don't even have to be restarted.

.SH AUTHOR
.B sysprof
was written by Soren Sandmann <sandmann@redhat.com>.
.PP
This manual page was written by Samuel Mimram <smimram@debian.org>,
for the Debian project (but may be used by others).
